apiVersion: v1
kind: Service
metadata:
  name: mxpv2-orchestrator
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  selector:
    app: mxpv2-orchestrator