//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integration.Orchestrator.Backend.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Integration.Orchestrator.Backend.Domain.Resources.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado no encontrado.
        /// </summary>
        public static string Application_StatusNotFound {
            get {
                return ResourceManager.GetString("Application_StatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No debe exceder los {0} caracteres.
        /// </summary>
        public static string Application_Validator_MaxLength {
            get {
                return ResourceManager.GetString("Application_Validator_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a se requiere.
        /// </summary>
        public static string Application_Validator_Required {
            get {
                return ResourceManager.GetString("Application_Validator_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El adaptador existe.
        /// </summary>
        public static string Domain_AdapterExists {
            get {
                return ResourceManager.GetString("Domain_AdapterExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La entidad existe.
        /// </summary>
        public static string Domain_EntitiesExists {
            get {
                return ResourceManager.GetString("Domain_EntitiesExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de entidad para este repositorio ya existe.
        /// </summary>
        public static string Domain_EntityRepositoryExists {
            get {
                return ResourceManager.GetString("Domain_EntityRepositoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proceso debe tener al menos dos registros.
        /// </summary>
        public static string Domain_IntegrationMinTwoRequired {
            get {
                return ResourceManager.GetString("Domain_IntegrationMinTwoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El prefijo {0} no está parametrizado.
        /// </summary>
        public static string Domain_NonParameterizedPrefix {
            get {
                return ResourceManager.GetString("Domain_NonParameterizedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de la propiedad para esta entidad ya existe.
        /// </summary>
        public static string Domain_PropertyEntityExists {
            get {
                return ResourceManager.GetString("Domain_PropertyEntityExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La propiedad existe.
        /// </summary>
        public static string Domain_PropertyExists {
            get {
                return ResourceManager.GetString("Domain_PropertyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El repositorio existe.
        /// </summary>
        public static string Domain_RepositoryExists {
            get {
                return ResourceManager.GetString("Domain_RepositoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo en uso.
        /// </summary>
        public static string Domain_Response_CodeInUse {
            get {
                return ResourceManager.GetString("Domain_Response_CodeInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creado Correctamente.
        /// </summary>
        public static string Domain_ResponseCode_CreatedSuccessfully {
            get {
                return ResourceManager.GetString("Domain_ResponseCode_CreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminado Correctamente.
        /// </summary>
        public static string Domain_ResponseCode_DeletedSuccessfully {
            get {
                return ResourceManager.GetString("Domain_ResponseCode_DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encontrado Correctamente.
        /// </summary>
        public static string Domain_ResponseCode_FoundSuccessfully {
            get {
                return ResourceManager.GetString("Domain_ResponseCode_FoundSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro no se puede activar porque el/los {0} no está(n) activo(s)..
        /// </summary>
        public static string Domain_ResponseCode_NotActivatedDueToInactiveRelationship {
            get {
                return ResourceManager.GetString("Domain_ResponseCode_NotActivatedDueToInactiveRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Creado Correctamente.
        /// </summary>
        public static string Domain_ResponseCode_NotCreatedSuccessfully {
            get {
                return ResourceManager.GetString("Domain_ResponseCode_NotCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Eliminado Correctamente.
        /// </summary>
        public static string Domain_ResponseCode_NotDeletedSuccessfully {
            get {
                return ResourceManager.GetString("Domain_ResponseCode_NotDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No es posible inactivar el registro porque está siendo utilizado en otro módulo..
        /// </summary>
        public static string Domain_ResponseCode_NotDeleteDueToRelationship {
            get {
                return ResourceManager.GetString("Domain_ResponseCode_NotDeleteDueToRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo no encontrado.
        /// </summary>
        public static string Domain_ResponseCode_NotFoundCodeSuccessfully {
            get {
                return ResourceManager.GetString("Domain_ResponseCode_NotFoundCodeSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Encontrado Correctamente.
        /// </summary>
        public static string Domain_ResponseCode_NotFoundSuccessfully {
            get {
                return ResourceManager.GetString("Domain_ResponseCode_NotFoundSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Actualizado Correctamente.
        /// </summary>
        public static string Domain_ResponseCode_NotUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("Domain_ResponseCode_NotUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Validado Correctamente.
        /// </summary>
        public static string Domain_ResponseCode_NotValidationSuccessfully {
            get {
                return ResourceManager.GetString("Domain_ResponseCode_NotValidationSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizado Correctamente.
        /// </summary>
        public static string Domain_ResponseCode_UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("Domain_ResponseCode_UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El servidor existe.
        /// </summary>
        public static string Domain_ServerExists {
            get {
                return ResourceManager.GetString("Domain_ServerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las integraciones deben contener al menos un valor.
        /// </summary>
        public static string Synchronization_Integrations_MinimumValue {
            get {
                return ResourceManager.GetString("Synchronization_Integrations_MinimumValue", resourceCulture);
            }
        }
    }
}
