# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- develop

resources:
- repo: self

variables:
  tag: 1.0.2 #'$(Build.BuildId)'

stages:
- stage: buildAndPush
  displayName: Build image and Push in ACR
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        containerRegistry: SC_DEV_KFC
        repository: mxpv2-integration-admin-back
        buildContext: '$(Build.SourcesDirectory)/'
        dockerfile: '$(Build.SourcesDirectory)/Integration.Orchestrator.Backend.Api/Dockerfile'
        tags: |
          $(tag)

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact'
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'publishAksMxpv2IntegrationAdminBack'
        publishLocation: 'pipeline'
